### PR TITLE
Link against libcurl-impersonate statically

### PR DESCRIPTION
**Pull request by bjia56**
Follow up to discussion in #255

### CODE REVIEW

**Comment by bjia56** [comment]
Looks like this might be more challenging than expected. The archive doesn't seem to include boringssl, it may only include libcurl's code.

**Comment by yifeikong** [comment]
Yes, I tried this yesterday and didn’t succeed two. I think an easier approach is to simply add rpath link args

**Comment by bjia56** [comment]
I think I can unblock my arm32 use case with 0.6.1 by pulling in the libraries before building the wheel from sdist and then running auditwheel, but that won't fix piwheels

**Comment by bjia56** [comment]
Ah looks like I will need #255 to be released for that

**Comment by bjia56** [comment]
I'll just manually download the so's for now

**Comment by yifeikong** [comment]
BTW, I'm getting `illgal instructions` on my Raspberry Pi Zero 2(armv6l) for some sites. I tested two websites:

- https://www.baidu.com, works
- https://www.zhihu.com, illegal instruction

**Comment by bjia56** [comment]
Can you post the output of this when running on that board:
```gcc -mcpu=native -march=native -Q --help=target```

**Comment by bjia56** [comment]
@yifeikong would you be open to bundling libz.a and libbrotli.a with the libcurl-impersonate tarball? I think that might enable this to work

**Comment by yifeikong** [comment]
Sure, go ahead and add them. I think the tricks I just added on main branch already make dynamic linking work as expected, but static linking is definitely better.

**Comment by bjia56** [comment]
@yifeikong I think this is ready for review/merge. Was able to get the sdist tarball to build on my Raspberry Pi 1 and 3 (armv6l and armv7l respectively).

I reverted the libcurl.so changes you made in the main branch since there's no longer a need to download into the archive and remove the extra libs.

Note that this PR is pointing to the prerelease curl-impersonate, so that will need to point to a proper release before publishing.

**Pull request merged**
