### PR TITLE
switch arm to use gnueabihf

### PR DESCRIPTION
**Pull request by bjia56**

### CODE REVIEW

**Comment by bjia56** [comment]
Looks like we should be good now:
```
pi@raspberrypi3:/tmp $ pip install curl_cffi-0.6.1.tar.gz
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing ./curl_cffi-0.6.1.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting cffi>=1.12.0
  Using cached https://www.piwheels.org/simple/cffi/cffi-1.16.0-cp39-cp39-linux_armv7l.whl (367 kB)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from curl_cffi==0.6.1) (2020.6.20)
Collecting pycparser
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /simple/pycparser/pycparser-2.21-py2.py3-none-any.whl
  Using cached https://www.piwheels.org/simple/pycparser/pycparser-2.21-py2.py3-none-any.whl (119 kB)
Building wheels for collected packages: curl-cffi
  Building wheel for curl-cffi (PEP 517) ... done
  Created wheel for curl-cffi: filename=curl_cffi-0.6.1-cp38-abi3-linux_armv7l.whl size=81384 sha256=5ef4abedcb145d003b957caf15501b0c85e8edea1affa5c2ebd9c691d79a756f
  Stored in directory: /home/pi/.cache/pip/wheels/20/9e/ed/9483649865051342a72f27fdc6d48f3978792446292291a5c7
Successfully built curl-cffi
Installing collected packages: pycparser, cffi, curl-cffi
Successfully installed cffi-1.16.0 curl-cffi-0.6.1 pycparser-2.21
```

**Comment by bjia56** [comment]
Ah but then:
```
pi@raspberrypi3:/tmp $ python3
Python 3.9.2 (default, Mar 12 2021, 04:06:34)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import curl_cffi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.9/site-packages/curl_cffi/__init__.py", line 18, in <module>
    from ._wrapper import ffi, lib  # type: ignore
ImportError: libcurl-impersonate-chrome.so.4: cannot open shared object file: No such file or directory
>>>
```

**Comment by bjia56** [comment]
```
pi@raspberrypi3:/tmp $ ls ~/.local/lib
libcurl-impersonate-chrome.a  libcurl-impersonate-chrome.la  libcurl-impersonate-chrome.so  libcurl-impersonate-chrome.so.4  libcurl-impersonate-chrome.so.4.8.0  python3.9
```

**Comment by yifeikong** [comment]
Yes, the delimma here is that:

1. If we put the dynamic libs inside `/usr/local/lib` or some other system path, it would require root when installing.
2. If we put them inside `~/.local/lib`, we have to set `LD_LIBRARY_PATH` at runtime.

Do you have better suggestions?

**Comment by bjia56** [comment]
Any chance we can statically link against libcurl? There are .a files in the tarball so I'd imagine we could make the wrapper statically link against it?

**Comment by yifeikong** [comment]
Good point, we should link to the `.a` files.

**Pull request merged**
