### PR TITLE
Add server ip address to response object

### PR DESCRIPTION
**Pull request by embeddinglayer**
Ideally the response object should include the established server ip. Curl already offers that which is a better alternative to opening an entirely new socket connection to resolve that data.

```python
import curl_cffi.requests as requests

resp = requests.get("https://example.com")
print(resp.ip)
```

### CODE REVIEW

**Comment by embeddinglayer** [comment]
Ideally the response object contains more data for the underlying connection such as  CURLINFO_CERTINFO and CURLINFO_TLS_SESSION

**Comment by yifeikong** [comment]
Interesting idea! However, it seems that there is no such const as `CURLINFO_NUM_CERTS`.

**Comment by embeddinglayer** [comment]
> Interesting idea! However, it seems that there is no such const as `CURLINFO_NUM_CERTS`.

Yeah, that code was unintentional looks like vs-code hadn't persisted to disk when I git committed. Removing.

**Comment by yifeikong** [comment]
We need one or two unittests to make sure that this patch works as expected. Feel free to add them now or leave it there and I will add them later.

**Pull request merged**
